[package]
name = "step_thumbnailer"
version = "0.1.0"
authors = ["jer<alphastrata@gmail.com>"]
edition = "2024"

[dependencies]
step = { path = "../step", features = ["parallel"] }
triangulate = { path = "../triangulate", features = ["parallel"] }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
itertools = { workspace = true }
nalgebra-glm = { workspace = true }
nalgebra = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
png.workspace = true
log.workspace = true
bytemuck = { workspace = true }
tracing.workspace = true
tracing-subscriber.workspace = true

meshopt = "0.6.1"
opencascade = { version = "0.2.0", optional = true }

[features]
default = []
occt = ["dep:opencascade"]
