[package]
name = "gui"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2024"

[features]
bundle-shaders = []

[dependencies]
step = { path = "../step", features = ["parallel"] }
triangulate = { path = "../triangulate", features = ["parallel"] }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
itertools = { workspace = true }
nalgebra-glm = { workspace = true }
pollster = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
bytemuck = { workspace = true }
