[package]
name = "step"
version = "0.1.0"
authors = ["Matt Keeter <matt.j.keeter@gmail.com>"]
edition = "2024"

[dependencies]
arrayvec = { workspace = true }
fast-float = { workspace = true }
log = { workspace = true }
memchr = { workspace = true }
nom = { workspace = true }
rayon = { workspace = true, optional = true }
ahash = { workspace = true }

[features]
rayon = ["dep:rayon"]

[dev-dependencies]
clap = { workspace = true }
