[package]
name = "cdt"
version = "0.1.0"
authors = ["Matt Keeter <matt@formlabs.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Formlabs/foxtrot"
homepage = "https://github.com/Formlabs/foxtrot/tree/master/cdt"
description = "Fast, robust constrained Delaunay triangulation"
readme = "README.md"
keywords = ["graphics", "triangulation", "delaunay"]
categories = ["graphics", "mathematics", "algorithms"]

[dependencies]
geometry-predicates = { workspace = true }
thiserror = { workspace = true }

[features]
long-indexes = []

[dev-dependencies]
clap = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rusttype = { workspace = true }
